### ISSUE TITLE
Obtain moon surface images

### ISSUE THREAD

**Issue by groovy-phazuma** [groovy-phazuma/Moon_Pattern_Inference#1]
- 月面のマリアを検出するための画像
- 各国の画像を同一バッチで格納しているところから引っ張ってきたい。いずれ拡張するので。

**Comment by groovy-phazuma** [comment]
勘違いしていたが、各国で見える月面自体は同じか。裏側は誰も見えない。
同一画像を回転すれば各国からの見え方を再現できる。

**Comment by groovy-phazuma** [comment]
NASAのデータベースより取得した。
PIA 00405 (credit: NASA/JPL/USGS)
https://science.nasa.gov/image-detail/amf-pia00405/

**Comment by KatsuhisaMorita** [comment]
well done!
