### ISSUE TITLE
Survey for classification models

### ISSUE THREAD

**Issue by groovy-phazuma** [groovy-phazuma/Moon_Pattern_Inference#6]
#### 実装・ベンチマーク対象とする手法の調査
せっかくなので馴染みがないような手法にも挑戦したい。
ImageNetでの性能: https://paperswithcode.com/sota/image-classification-on-imagenet

- [ResNet](https://pytorch.org/hub/pytorch_vision_resnet/) ベースラインか
- [DenseNet](https://pytorch.org/hub/pytorch_vision_densenet/) ベースラインか
- [ViT](https://pytorch.org/vision/main/models/generated/torchvision.models.vit_b_16.html) グラフとの相性も良くて後学のためにも是非
- [gradcam](https://github.com/jacobgil/pytorch-grad-cam) 任意のCNNモデルに後付けできるという理解？要調査。
- [lion](https://github.com/lucidrains/lion-pytorch) imagenetのスコアでSOTA

**Comment by KatsuhisaMorita** [comment]
SSLで比較に用いたCNNモデルは
1. ResNet
2. EfficientNet
3. Regnet
4. densenet
5. convnext
の5つで、torchvisionにて実装されている (https://pytorch.org/vision/stable/models.html)

GradCamは任意のCNNでgradを逆計算足し合わせしてヒートマップを得ることが可能。
（SSL病理画像で実装したことあり）

**Comment by KatsuhisaMorita** [comment]
月の"シルエット"を認識したい場合、ViTがその性質にあっている
月の"テクスチャ"を認識したい場合、CNNがよさそう。
ヒトの認識性はシルエットによっているので、ViTの方がより直感にはあっている。
参考: https://qiita.com/wakayama_90b/items/e2c9f5e65aec08ffc122

モデルは動かせるようにしつつ、
* Model architectures
1. ViT (本命、transformerのbaseline)
2. Swin Transformer (ViTの改善版らしい)
3. ResNet (CNN baseline)
4. ConvNext (ResNetよりいろいろ改善したもの)
の4つ程度を用いればよいのではないか。

* 解釈性
1. Attentionを用いる（transformer系）
2. GradCam（そこそこスタンダード）
3. RISE（領域系のスタンダード）

このあたりか
問題なければcloseお願いします。

**Comment by groovy-phazuma** [comment]
あざす。確認しました。
