### ISSUE TITLE
Prepare silhouette dataset (labeled)

### ISSUE THREAD

**Issue by KatsuhisaMorita** [groovy-phazuma/Moon_Pattern_Inference#7]
**学習用データセットの準備**

* ImageNetより加工する
1. シルエットの抽出
1. Grey Scaleでの定義
このあたりは、月の画像の加工にも依存するか。

* 生成AIの利用
1. ラベルとシルエット、白黒などの情報を与えて画像を生成してもらう
ただ、学習に使える程度の量を用意するには課金が必要か？
”動作”を含ませることができるか

* その他
1. シルエット画像を載せているフリーのところから画像のラベル収集
例: https://www.silhouette-ac.com/

**Comment by groovy-phazuma** [comment]
[先行研究](https://arxiv.org/pdf/1708.05636.pdf)の手法も参考になりそうですね。

> The numbers of collected silhouette images of the crab, lion and hare were 100, 100 and
105, respectively (I bought silhouette images from Deposit Photos (https://jp.depositphotos.com/),
and downloaded free images from Silhouette AC (https://www.silhouette-ac.com/index.html),
Illust AC (https://www.ac-illust.com), Clipart Library (http://clipart-library.com), Silhouette Design (http://kage-design.com/)). Example images are shown in Fig. 3. Of
these 305 images, 240 images (80 images in each class) were used for training of the CNNs
and 65 images were used as the test data set. The size of each image was 50×50 pixels
and the intensity of the images was normalized between 0 and 1 by dividing each intensity
by 255.

**Comment by KatsuhisaMorita** [comment]
そもそもImageNetのsegmentation用に準備されたデータセットを援用できるかもしれない。
https://github.com/LUSSeg/ImageNet-S

**Comment by KatsuhisaMorita** [comment]
231127
data1/ImageNet下にデータセットをダウンロード

**Comment by KatsuhisaMorita** [comment]
231128
ImageNet-S
データセットを展開。

https://github.com/LUSSeg/ImageNet-S
Image Numbers
The ImageNet-S dataset contains 1183322 training, 12419 validation, and 27423 testing images from 919 categories. We annotate 39842 val/test images and 9190 training images with precise pixel-level masks.

具体的に使えそうか、見る。
